// Единый каталог блюд NiloV — 78 уникальных SKU
// Источник: 23_MENU_STRATEGY.md, 04_BLOCKS.md
// Все цены pending-verification
import type { Dish } from './types';

// ═══════════════════════════════════════════
// §1 — ТРЕНД-ЯКОРЯ 2026
// ═══════════════════════════════════════════

// 1. Global small plates (7 SKU)
const GLOBAL_SMALL_PLATES: Dish[] = [
  { id: 'bao-pork', name: 'Бао с томлёной свининой', description: 'Паровые булочки с томлёной свининой, хойсином и свежим огурцом. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 350, servingsPerGuest: 1, allergens: ['gluten', 'soy', 'sesame'], dietBadges: [], childFriendly: false },
  { id: 'bao-duck', name: 'Бао с уткой и хойсином', description: 'Утка конфи, хойсин, зелёный лук в паровой булочке. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['gluten', 'soy', 'sesame'], dietBadges: [], childFriendly: false },
  { id: 'taco-fish', name: 'Мини-тако с рыбой', description: 'Кукурузная тортилья, белая рыба, сальса, лайм. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'hot', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 1, allergens: ['fish'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'taco-cauliflower', name: 'Мини-тако с цветной капустой', description: 'Кукурузная тортилья, цветная капуста с чимичурри, веган. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'hot', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'poke-salmon', name: 'Поке с лососем и авокадо', description: 'Рис, лосось, авокадо, эдамамэ, соус понзу (содержит пшеницу через соевый соус). ХЕ=0, БЖУ: белки 18 г / жиры 8 г / углеводы 2 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 420, servingsPerGuest: 1, allergens: ['fish', 'soy', 'sesame', 'gluten'], dietBadges: [], childFriendly: false },
  { id: 'thai-meatballs', name: 'Тайские мясные шарики с чили', description: 'Свинина/говядина, лемонграсс, чили, рыбный соус. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 300, servingsPerGuest: 1, allergens: ['fish', 'soy'], dietBadges: [], childFriendly: false },
  { id: 'jerk-chicken', name: 'Джерк-курица на плантане', description: 'Куриное бедро в джерк-маринаде на жареном плантане. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 360, servingsPerGuest: 1, allergens: [], dietBadges: ['gluten-free'], childFriendly: false },
];

// 2. Plant-based mains (6 SKU)
const PLANT_BASED: Dish[] = [
  { id: 'cauli-steak', name: 'Стейк из цветной капусты с тапенадой', description: 'Цельный стейк из цветной капусты, тапенада из оливок. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 340, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'zucchini-curry', name: 'Цуккини-пюре с кокосовым карри', description: 'Кремовое пюре из цуккини с кокосовым карри и киноа. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'hot', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'beet-carpaccio', name: 'Карпаччо из свёклы с дымком', description: 'Тонкие слайсы свёклы, козий сыр, руккола, бальзамик. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'mushroom-burger', name: 'Бургер из грибов и бобов', description: 'Котлета из шампиньонов и чёрных бобов, булочка бриошь, соус. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 290, servingsPerGuest: 1, allergens: ['gluten', 'soy', 'sesame'], dietBadges: [], childFriendly: true },
  { id: 'veggie-ragout', name: 'Овощное рагу', description: 'Сезонные овощи, томатный соус, базилик. ХЕ=0.5, БЖУ: белки 3 г / жиры 5 г / углеводы 6 г.', image: '', station: 'hot', format: ['banket', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 250, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free', 'sugar-free'], childFriendly: true },
  { id: 'buddha-bowl', name: 'Будда-боул с тофу', description: 'Киноа, тофу, авокадо, эдамамэ, мисо-дрессинг. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['soy', 'sesame'], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
];

// 4. Grazing table (5 SKU)
const GRAZING: Dish[] = [
  { id: 'meat-platter', name: 'Мясное плато', description: 'Буженина, ростбиф, индейка, горчица, корнишоны. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 450, servingsPerGuest: 1, allergens: ['mustard'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'cheese-platter', name: 'Сырная тарелка', description: 'Камамбер, маасдам, пармезан, мёд, орехи. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 420, servingsPerGuest: 1, allergens: ['milk', 'nuts'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'burrata-tomatoes', name: 'Буррата + томаты', description: 'Свежая буррата, томаты черри, базилик. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'antipasto', name: 'Антипасто-плато', description: 'Прошутто, салями, артишоки, оливки. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 480, servingsPerGuest: 1, allergens: [], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'vegan-grazing', name: 'Веган-грэзинг', description: 'Овощи гриль, хумус, оливки, пита. ХЕ=0.5, БЖУ: белки 3 г / жиры 5 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 1, allergens: ['gluten', 'sesame'], dietBadges: ['vegan'], childFriendly: true },
];

// 5. Dessert stations (8 SKU)
const DESSERTS: Dish[] = [
  { id: 'macaron-shooter', name: 'Макаронс-шутер', description: '3 мини-макаронс в дегустационном стакане. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'coffee-break', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 220, servingsPerGuest: 1, allergens: ['nuts', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'donut-wall', name: 'Донат-стена', description: 'Мини-донаты с глазурью, оформление стеной (может содержать следы орехов). ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk', 'nuts'], dietBadges: [], childFriendly: true },
  { id: 'cheesecake-shooter', name: 'Чизкейк-шутер', description: 'Классический чизкейк в стакане с ягодным кули. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['banket', 'coffee-break'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: ['milk', 'eggs', 'gluten'], dietBadges: [], childFriendly: true },
  { id: 'choc-mousse', name: 'Шоколадный мусс (веган, без сахара)', description: 'Из авокадо и тёмного шоколада без добавленного сахара (стевия). ХЕ=1.5, БЖУ: белки 3 г / жиры 10 г / углеводы 18 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 190, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free', 'sugar-free'], childFriendly: true },
  { id: 'chia-pudding', name: 'Веррин чиа-пудинг (без сахара)', description: 'Кокосовое молоко, чиа, манго, маракуйя без добавленного сахара. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 170, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free', 'sugar-free'], childFriendly: true },
  { id: 'brownie-shooter', name: 'Брауни-шутер', description: 'Шоколадный брауни в стакане с карамелью (с грецким орехом). ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'coffee-break', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 190, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk', 'nuts'], dietBadges: [], childFriendly: true },
  { id: 'cookie-shooter', name: 'Молочно-печенье-шутер', description: 'Крошка печенья, ванильный крем, карамель. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs'], dietBadges: [], childFriendly: true },
  { id: 'mini-tart', name: 'Мини-тарт-ассорти', description: 'Лимонный, ягодный, шоколадный. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'coffee-break', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
];

// 6. Signature drinks (7 SKU)
const DRINKS: Dish[] = [
  { id: 'seabuckthorn-tea', name: 'Облепиховый чай с имбирём', description: 'Согревающий чай с облепихой и имбирём. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket', 'coffee-break'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 120, servingsPerGuest: 2, allergens: [], dietBadges: ['vegan', 'gluten-free', 'sugar-free'], childFriendly: true },
  { id: 'cranberry-mors', name: 'Клюквенный морс с мятой', description: 'Домашний морс из клюквы с мятой и лаймом. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket', 'coffee-break'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 100, servingsPerGuest: 2, allergens: [], dietBadges: ['vegan', 'gluten-free', 'sugar-free'], childFriendly: true },
  { id: 'cedar-raf', name: 'Кедровый раф', description: 'Кофейный напиток с кедровым молоком (содержит кедровый орех). ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket', 'coffee-break'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 150, servingsPerGuest: 1, allergens: ['milk', 'nuts'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'lemonade-tarragon', name: 'Лимонад эстрагон', description: 'Авторский лимонад с эстрагоном и лаймом. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket', 'coffee-break', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 100, servingsPerGuest: 2, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'lemonade-berry', name: 'Лимонад ягодный', description: 'Микс ягод, лимон, мята, содовая. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket', 'coffee-break', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 110, servingsPerGuest: 2, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'kombucha', name: 'Комбуча', description: 'Ферментированный чайный напиток. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 140, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: false },
  { id: 'welcome-drink', name: 'Приветственный напиток', description: 'Игристое + канапе с лососем. ХЕ=0.5, БЖУ: белки 3 г / жиры 4 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 350, servingsPerGuest: 1, allergens: ['fish', 'gluten'], dietBadges: [], childFriendly: false },
];

// ═══════════════════════════════════════════
// §2 — ФОРМАТНЫЕ ЛИНИИ
// ═══════════════════════════════════════════

// ФУРШЕТ (11 дополнительных)
const FURSHET_EXTRA: Dish[] = [
  { id: 'canape-salmon', name: 'Канапе с лососем', description: 'Сливочный сыр, лосось, укроп. ХЕ=0.5, БЖУ: белки 3 г / жиры 4 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 190, servingsPerGuest: 2, allergens: ['fish', 'milk', 'gluten'], dietBadges: [], childFriendly: true },
  { id: 'canape-caviar', name: 'Канапе с красной икрой', description: 'Икра лососёвая, сливочное масло, тарталетка. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'cold', format: ['furshet'], tier: ['premium', 'luxury'], pricePerGuest: 250, servingsPerGuest: 1, allergens: ['fish', 'gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: false },
  { id: 'tartaletka-olivier', name: 'Тарталетка с оливье', description: 'Мини-оливье в песочной тарталетке. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'cold', format: ['furshet'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'bruschetta-tomato', name: 'Брускетта с томатами', description: 'Чиабатта, томаты, базилик, чеснок. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'cold', format: ['furshet'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 140, servingsPerGuest: 1, allergens: ['gluten'], dietBadges: [], childFriendly: true },
  { id: 'canape-caprese', name: 'Канапе «Капрезе»', description: 'Моцарелла, томаты черри, песто. ХЕ=0.5, БЖУ: белки 4 г / жиры 8 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['milk', 'nuts'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'lavash-roll', name: 'Рулетик из лаваша', description: 'Лаваш, курица, сыр, зелень. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'cold', format: ['furshet', 'mobile-furshet'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 150, servingsPerGuest: 1, allergens: ['gluten', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'mini-burger', name: 'Мини-бургер', description: 'Котлета свинина/курица, булочка, сыр. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 250, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs'], dietBadges: [], childFriendly: true },
  { id: 'yakitori', name: 'Куриные якитори', description: 'Шпажки в соусе терияки с кунжутом (содержит пшеницу через соевый соус). ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'hot', format: ['furshet', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 220, servingsPerGuest: 1, allergens: ['soy', 'sesame', 'gluten'], dietBadges: [], childFriendly: true },
  { id: 'veggie-grill', name: 'Овощи гриль', description: 'Баклажан, перец, цуккини, шампиньоны. ХЕ=0.5, БЖУ: белки 3 г / жиры 5 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'prophyroles', name: 'Профитроли с грибами', description: 'Заварное тесто, грибной мусс. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'hot', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 230, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: false },
  { id: 'chocolate-brownie', name: 'Шоколадный брауни', description: 'Классический брауни с грецким орехом. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['furshet', 'coffee-break', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk', 'nuts'], dietBadges: [], childFriendly: true },
];

// БАНКЕТ (11 дополнительных)
const BANKET_EXTRA: Dish[] = [
  { id: 'borscht', name: 'Борщ', description: 'Классический со сметаной и пампушками. ХЕ=1, БЖУ: белки 6 г / жиры 4 г / углеводы 12 г.', image: '', station: 'hot', format: ['banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 1, allergens: ['gluten', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'okroshka', name: 'Окрошка (сезон)', description: 'На квасе или кефире, свежие овощи. ХЕ=1, БЖУ: белки 6 г / жиры 4 г / углеводы 12 г.', image: '', station: 'cold', format: ['banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 250, servingsPerGuest: 1, allergens: ['eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'mushroom-soup', name: 'Крем-суп из белых грибов', description: 'Сливки, белые грибы, трюфельное масло. ХЕ=1, БЖУ: белки 6 г / жиры 4 г / углеводы 12 г.', image: '', station: 'hot', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 350, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'caesar', name: 'Салат Цезарь', description: 'Романо, курица, пармезан, гренки. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'cold', format: ['banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs', 'fish'], dietBadges: [], childFriendly: true },
  { id: 'salmon-salad', name: 'Салат с лососем и авокадо', description: 'Микс салатов, лосось, авокадо. ХЕ=0.5, БЖУ: белки 4 г / жиры 8 г / углеводы 6 г.', image: '', station: 'cold', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['fish'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'beef-stroganoff', name: 'Бефстроганов', description: 'Говяжья вырезка, сливочный соус, пюре. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 480, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'beef-medallions', name: 'Медальоны из вырезки', description: 'Говядина, перечный соус, розмарин. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['banket'], tier: ['premium', 'luxury'], pricePerGuest: 580, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'trout', name: 'Форель с картофельным муссом', description: 'Филе форели, картофельный мусс, шпинат. ХЕ=0, БЖУ: белки 18 г / жиры 8 г / углеводы 2 г.', image: '', station: 'hot', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 520, servingsPerGuest: 1, allergens: ['fish', 'milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'chicken-quinoa', name: 'Курица с киноа', description: 'Куриное филе, киноа, овощи, лимон. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'hot', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: [], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'tiramisu', name: 'Тирамису', description: 'Классическое в порционной подаче. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'desserts', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 250, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: false },
  { id: 'apple-tart', name: 'Яблочный тарт', description: 'Тонкое тесто, яблоки, корица. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 220, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'gluten-free-cake', name: 'БГ торт на день рождения (рисовая мука)', description: 'Безглютеновый торт на рисовой муке (ТМ Гарнец 1:1), крем из маскарпоне, ягоды. <20 ppm. Без орехов. ХЕ=1.5, БЖУ: белки 6 г / жиры 18 г / углеводы 18 г.', image: '', station: 'desserts', format: ['furshet', 'banket', 'detskoe'], tier: ['premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['milk', 'eggs'], dietBadges: ['gluten-free', 'nut-free'], childFriendly: true },
  { id: 'gluten-free-cupcakes', name: 'БГ капкейки', description: 'Безглютеновые капкейки на рисовой муке (ТМ Гарнец), крем-чиз. <20 ppm. Без орехов. ХЕ=1.5, БЖУ: белки 4 г / жиры 12 г / углеводы 18 г.', image: '', station: 'desserts', format: ['furshet', 'detskoe', 'coffee-break'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 220, servingsPerGuest: 1, allergens: ['milk', 'eggs'], dietBadges: ['gluten-free', 'nut-free'], childFriendly: true },
  { id: 'gluten-free-pizza', name: 'БГ мини-пицца (рисовая мука)', description: 'Безглютеновая пицца на рисовой муке, томаты, моцарелла, базилик. <20 ppm. Без орехов. ХЕ=1.5, БЖУ: белки 8 г / жиры 12 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'detskoe'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free', 'nut-free'], childFriendly: true },
];

// КОФЕ-БРЕЙК (5 дополнительных)
const COFFEE_BREAK_EXTRA: Dish[] = [
  { id: 'croissant', name: 'Круассан', description: 'Классический масляный. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['coffee-break'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 130, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'eclair', name: 'Эклер', description: 'Заварное тесто, ванильный крем, глазурь. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['coffee-break'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 150, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'muffin', name: 'Маффин', description: 'Черничный или шоколадный. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['coffee-break', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 140, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'mini-sandwich', name: 'Мини-сэндвич', description: 'Ветчина, сыр, огурец на бриоши. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'cold', format: ['coffee-break'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: ['gluten', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'fruit-platter', name: 'Фруктовая тарелка', description: 'Сезонные фрукты. ХЕ=1, БЖУ: белки 1 г / жиры 0 г / углеводы 12 г.', image: '', station: 'cold', format: ['coffee-break', 'furshet', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free', 'sugar-free'], childFriendly: true },
];

// СВАДЬБА (2)
const WEDDING_EXTRA: Dish[] = [
  { id: 'wedding-cake', name: 'Свадебный торт', description: 'Индивидуальный от кондитера, 3 яруса. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 1500, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk', 'nuts'], dietBadges: [], childFriendly: true },
  { id: 'soup-shooter', name: 'Суп-шутер', description: 'Борщ/окрошка в дегустационном стакане. ХЕ=1, БЖУ: белки 6 г / жиры 4 г / углеводы 12 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['milk'], dietBadges: [], childFriendly: false },
];

// ═══════════════════════════════════════════
// §7 — ДЕТСКОЕ МЕНЮ (9 блюд)
// ═══════════════════════════════════════════
const KIDS: Dish[] = [
  { id: 'kids-burger', name: 'Мини-бургер (детский)', description: 'Куриная котлета, булочка, сыр. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 220, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs'], dietBadges: [], childFriendly: true },
  { id: 'nuggets', name: 'Наггетсы', description: 'Куриные наггетсы, кетчуп. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'hot', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'eggs'], dietBadges: [], childFriendly: true },
  { id: 'mini-pizza', name: 'Мини-пицца', description: 'Томатный соус, сыр, ветчина. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 170, servingsPerGuest: 1, allergens: ['gluten', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'pasta-cheese', name: 'Паста с сыром', description: 'Макароны, сливочный сырный соус. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'hot', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: ['gluten', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'fruit-canape', name: 'Фруктовые канапе', description: 'Клубника, банан, виноград. ХЕ=0.5, БЖУ: белки 3 г / жиры 4 г / углеводы 6 г.', image: '', station: 'cold', format: ['detskoe', 'furshet'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 140, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'pancakes', name: 'Панкейки', description: 'Мини-панкейки с ягодным соусом. ХЕ=1, БЖУ: белки 1 г / жиры 0 г / углеводы 12 г.', image: '', station: 'desserts', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 150, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'cupcakes', name: 'Капкейки', description: 'С кремом и посыпкой. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['detskoe', 'coffee-break'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 170, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'milkshake', name: 'Молочный коктейль', description: 'Клубничный или шоколадный. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 130, servingsPerGuest: 1, allergens: ['milk'], dietBadges: [], childFriendly: true },
  { id: 'kids-fruit', name: 'Фруктовое ассорти', description: 'Нарезка свежих фруктов. ХЕ=1, БЖУ: белки 1 г / жиры 0 г / углеводы 12 г.', image: '', station: 'cold', format: ['detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
];

// §8 — БРАНЧИ (7 блюд)
const BRUNCH: Dish[] = [
  { id: 'croissant-ham', name: 'Круассан с ветчиной', description: 'Тёплый, с ветчиной и сыром. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'hot', format: ['coffee-break', 'furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs'], dietBadges: [], childFriendly: true },
  { id: 'omelette', name: 'Омлет', description: 'Нежный, с зеленью и сыром. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'hot', format: ['coffee-break', 'furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: ['eggs', 'milk'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'syrniki', name: 'Сырники', description: 'Творожные со сметаной и вареньем. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'hot', format: ['coffee-break', 'furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs'], dietBadges: [], childFriendly: true },
  { id: 'greek-yogurt', name: 'Греческий йогурт', description: 'С мёдом, гранолой и ягодами. ХЕ=0.5, БЖУ: белки 4 г / жиры 8 г / углеводы 6 г.', image: '', station: 'cold', format: ['coffee-break', 'furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: ['milk', 'gluten', 'nuts'], dietBadges: [], childFriendly: true },
  { id: 'fresh-juice', name: 'Свежевыжатый сок', description: 'Апельсиновый, грейпфрутовый. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['coffee-break', 'furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 150, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: true },
  { id: 'latte', name: 'Латте', description: 'Классический с молочной пенкой. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'drinks', format: ['coffee-break'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 120, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'eggs-benedict', name: 'Яичница-бенедикт', description: 'Яйцо пашот, бекон, голландский соус. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'hot', format: ['coffee-break', 'furshet'], tier: ['premium', 'luxury'], pricePerGuest: 350, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: false },
];

// ═══════════════════════════════════════════
// §6 — SHOW-COOKING (6 станций)
// ═══════════════════════════════════════════
export interface ShowCookingStation {
  id: string;
  name: string;
  description: string;
  pricePerPortion: number;
  stationCost: number;
  minPortions: number;
}

export const SHOW_COOKING_STATIONS: ShowCookingStation[] = [
  { id: 'volcanic-beef', name: 'Телятина на вулканическом камне', description: 'Шеф готовит на раскалённом вулканическом камне при гостях. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', pricePerPortion: 605, stationCost: 62500, minPortions: 100 },
  { id: 'whole-salmon', name: 'Запечённый мурманский лосось', description: 'Целый лосось запекается при вас с травами. ХЕ=0, БЖУ: белки 18 г / жиры 8 г / углеводы 2 г.', pricePerPortion: 605, stationCost: 72500, minPortions: 100 },
  { id: 'mexican-taco', name: 'Тако «Знойная Мексика»', description: 'Тако с начинками на выбор. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', pricePerPortion: 339, stationCost: 48500, minPortions: 75 },
  { id: 'parmesan-risotto', name: 'Ризотто в колесе пармезана', description: 'Ризотто доводится в головке пармезана. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', pricePerPortion: 605, stationCost: 64500, minPortions: 75 },
  { id: 'stroganina', name: 'Строганина из северных рыб', description: 'Тончайшие ломтики замороженной рыбы. ХЕ=0, БЖУ: белки 18 г / жиры 8 г / углеводы 2 г.', pricePerPortion: 484, stationCost: 56500, minPortions: 100 },
  { id: 'raclette-bar', name: 'Раклет-бар', description: 'Швейцарский раклет плавится при гостях. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', pricePerPortion: 0, stationCost: 40000, minPortions: 0 },
];

// §9 — ХАЛЯЛЬ-МЕНЮ (8 блюд, готовится на отдельной линии по запросу, от 3 рабочих дней)
const HALAL: Dish[] = [
  { id: 'halal-chicken-shashlik', name: 'Шашлык из курицы (халяль)', description: 'Куриное бедро в маринаде из йогурта и специй, мангал. Без свинины, без алкоголя. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['halal'], childFriendly: true },
  { id: 'halal-lamb-kofta', name: 'Кюфта из баранины (халяль)', description: 'Баранина рубленая с кинзой и зирой, гриль. Без свинины, без алкоголя. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 420, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'gluten-free'], childFriendly: false },
  { id: 'halal-beef-burger', name: 'Бургер с говядиной (халяль)', description: 'Говяжья котлета (халяль-забой), бриошь, чеддер, карамелизированный лук. Без свинины. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 290, servingsPerGuest: 1, allergens: ['gluten', 'milk', 'eggs'], dietBadges: ['halal'], childFriendly: true },
  { id: 'halal-plov', name: 'Плов с говядиной (халяль)', description: 'Узбекский плов с говядиной халяль, морковь, нут, зира. Без свинины. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'hot', format: ['banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 450, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'gluten-free'], childFriendly: true },
  { id: 'halal-samsa', name: 'Самса с курицей (халяль)', description: 'Слоёное тесто, куриная начинка, лук, специи. Без свинины, без алкоголя. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 220, servingsPerGuest: 1, allergens: ['gluten', 'milk'], dietBadges: ['halal'], childFriendly: true },
  { id: 'halal-kebab-plate', name: 'Кебаб-плато (халяль)', description: 'Ассорти из курицы, баранины и говядины халяль на гриле. Без свинины. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 520, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'gluten-free'], childFriendly: false },
  { id: 'halal-hummus', name: 'Хумус с питой (веганский, халяль)', description: 'Нут, тахини, лимон, чеснок. Подаётся с тёплой питой. Без животных жиров. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'sesame'], dietBadges: ['halal', 'vegan'], childFriendly: true },
  { id: 'halal-fattoush', name: 'Салат фаттуш (веганский, халяль)', description: 'Овощи, зелень, обжаренная пита, сумах. Без животных жиров. ХЕ=0.5, БЖУ: белки 4 г / жиры 8 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: ['gluten'], dietBadges: ['halal', 'vegan'], childFriendly: true },
  { id: 'halal-chicken-rice', name: 'Курица с рисом (халяль)', description: 'Курица халяль на гриле, рис басмати, томлёные овощи. Без свинины. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'hot', format: ['furshet', 'banket', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'gluten-free'], childFriendly: true },
  { id: 'halal-meatballs', name: 'Фрикадельки из говядины (халяль)', description: 'Говядина халяль, томатный соус, специи. Без свинины. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket', 'detskoe'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'gluten-free'], childFriendly: true },
  { id: 'halal-tabouleh', name: 'Табуле (веганский, халяль)', description: 'Булгур, петрушка, мята, томаты, лимон. Без животных жиров. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 190, servingsPerGuest: 1, allergens: ['gluten'], dietBadges: ['halal', 'vegan'], childFriendly: true },
  { id: 'halal-baklava', name: 'Пахлава (халяль)', description: 'Слоёное тесто, фисташки, мёд. Без свинины, без алкоголя. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'desserts', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 210, servingsPerGuest: 1, allergens: ['gluten', 'nuts', 'milk'], dietBadges: ['halal'], childFriendly: true },
  { id: 'halal-lentil-soup', name: 'Чечевичный суп (веганский, халяль)', description: 'Красная чечевица, томаты, зира, лимон. Без животных жиров. ХЕ=1, БЖУ: белки 6 г / жиры 4 г / углеводы 12 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'vegan', 'gluten-free'], childFriendly: true },
  { id: 'halal-grilled-veg', name: 'Овощи гриль (веганский, халяль)', description: 'Баклажан, цуккини, перец, шампиньоны на гриле. Без животных жиров. ХЕ=0.5, БЖУ: белки 3 г / жиры 5 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: [], dietBadges: ['halal', 'vegan', 'gluten-free'], childFriendly: true },
];

// §10 — ПРЕМИУМ-БЛЮДА для свадебных/корпоративных тарифов (28 SKU)
// Эти dishId используются в lib/tariff-offers.ts SVADBA/KORPORATIV/CHASTNOE/CHEF_AT_HOME
// Ранее отсутствовали в ALL_DISHES → аллергены и цены не показывались
const PREMIUM_EXTRA: Dish[] = [
  { id: 'canape-red-fish', name: 'Канапе с красной рыбой', description: 'Лосось слабой соли, сливочный сыр, укроп на бородинском хлебе. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 190, servingsPerGuest: 2, allergens: ['fish', 'milk', 'gluten'], dietBadges: [], childFriendly: true },
  { id: 'canape-cheese', name: 'Канапе с сыром', description: 'Сыр дор-блю, грецкий орех, медовые соты на крекере. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 170, servingsPerGuest: 2, allergens: ['milk', 'nuts', 'gluten'], dietBadges: [], childFriendly: true },
  { id: 'canape-ham', name: 'Канапе с хамоном', description: 'Хамон, дыня, руккола на багете. ХЕ=0.5, БЖУ: белки 3 г / жиры 4 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 1, allergens: ['gluten'], dietBadges: [], childFriendly: false },
  { id: 'tartlet-chicken', name: 'Тарталетка куриная', description: 'Копчёная курица, вяленые томаты, сливочный мусс. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 160, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'tartlet-mushroom', name: 'Тарталетка грибная', description: 'Шампиньоны, лисички, трюфельное масло. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 180, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'chicken-grill', name: 'Куриное филе гриль', description: 'Куриное филе су-вид, розмарин, чеснок, песто. ХЕ=0.5, БЖУ: белки 3 г / жиры 5 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 1, allergens: ['milk', 'nuts'], dietBadges: ['gluten-free'], childFriendly: true },
  { id: 'beef-steak', name: 'Стейк из говядины', description: 'Говядина Прайм, прожарка средняя, перечный соус. ХЕ=0.5, БЖУ: белки 20 г / жиры 12 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 580, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'salmon-grill', name: 'Лосось гриль', description: 'Филе лосося на гриле, лимонный бер-блан, спаржа. ХЕ=0, БЖУ: белки 18 г / жиры 8 г / углеводы 2 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 520, servingsPerGuest: 1, allergens: ['fish', 'milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'pasta-station', name: 'Живая паста-станция', description: 'Паста на выбор (спагетти/пенне/равиоли), 3 соуса, пармезан. ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'show', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 450, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'sushi-station', name: 'Суши-станция', description: 'Роллы Филадельфия, Калифорния, спайси тунец, поке. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'show', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 550, servingsPerGuest: 1, allergens: ['fish', 'soy', 'sesame'], dietBadges: [], childFriendly: false },
  { id: 'caviar-station', name: 'Икорная станция', description: 'Красная икра, чёрная икра, бриошь, сливочное масло, лимон. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 850, servingsPerGuest: 1, allergens: ['fish', 'gluten', 'milk'], dietBadges: [], childFriendly: false },
  { id: 'oyster-bar', name: 'Устричный бар', description: 'Устрицы фин де клер, лимон, соус миньонет. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 600, servingsPerGuest: 3, allergens: ['molluscs'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'tuna-tartare', name: 'Тартар из тунца', description: 'Тунец блюфин, авокадо, соус понзу (содержит пшеницу через соевый соус), кунжут. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 480, servingsPerGuest: 1, allergens: ['fish', 'soy', 'sesame', 'gluten'], dietBadges: [], childFriendly: false },
  { id: 'foie-gras', name: 'Фуа-гра на бриоши', description: 'Фуа-гра на бриоши, инжирное варенье, морская соль. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 720, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: false },
  { id: 'lobster-thermidor', name: 'Лобстер Термидор', description: 'Лобстер в сливочно-горчичном соусе, запечённый под пармезаном. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 980, servingsPerGuest: 1, allergens: ['crustaceans', 'milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'beef-wellington', name: 'Говядина Веллингтон', description: 'Говяжья вырезка в слоёном тесте с грибным дюкселем. ХЕ=1.5, БЖУ: белки 5 г / жиры 8 г / углеводы 18 г.', image: '', station: 'hot', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 890, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: false },
  { id: 'cheese-platter-premium', name: 'Сырная тарелка премиум', description: 'Бри де мо, горгонзола, манчего, трюфельный мёд, инжир. ХЕ=0.5, БЖУ: белки 7 г / жиры 15 г / углеводы 6 г.', image: '', station: 'cold', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 520, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'dessert-firework', name: 'Фейерверк-десерт', description: 'Шоколадная сфера, которая тает от горячей карамели, открывая мусс. ХЕ=1.5, БЖУ: белки 3 г / жиры 10 г / углеводы 18 г.', image: '', station: 'desserts', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 450, servingsPerGuest: 1, allergens: ['gluten', 'eggs', 'milk', 'nuts'], dietBadges: [], childFriendly: true },
  { id: 'mini-ekler', name: 'Мини-эклеры', description: 'Заварное тесто, ванильный крем, шоколадная глазурь. ХЕ=2, БЖУ: белки 4 г / жиры 12 г / углеводы 24 г.', image: '', station: 'desserts', format: ['furshet', 'banket'], tier: ['economy', 'standard', 'premium', 'luxury'], pricePerGuest: 150, servingsPerGuest: 2, allergens: ['gluten', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'macaron-tower', name: 'Башня макаронс', description: 'Многоярусная башня из макаронс (фисташка/малина/шоколад). ХЕ=2.5, БЖУ: белки 15 г / жиры 8 г / углеводы 30 г.', image: '', station: 'desserts', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 380, servingsPerGuest: 1, allergens: ['nuts', 'eggs', 'milk'], dietBadges: [], childFriendly: true },
  { id: 'wine-red', name: 'Вино красное', description: 'Красное сухое: Кьянти/Риоха/Кот дю Рон. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 350, servingsPerGuest: 2, allergens: ['sulphites'], dietBadges: ['vegan', 'gluten-free'], childFriendly: false },
  { id: 'wine-white', name: 'Вино белое', description: 'Белое сухое: Соаве/Альбариньо/Шабли. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 320, servingsPerGuest: 2, allergens: ['sulphites'], dietBadges: ['vegan', 'gluten-free'], childFriendly: false },
  { id: 'champagne', name: 'Шампанское', description: 'Игристое брют, просекко. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 450, servingsPerGuest: 2, allergens: ['sulphites'], dietBadges: ['vegan', 'gluten-free'], childFriendly: false },
  { id: 'champagne-premium', name: 'Шампанское премиум', description: 'Шампанское AOC, брют/розе. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 850, servingsPerGuest: 1, allergens: ['sulphites'], dietBadges: ['vegan', 'gluten-free'], childFriendly: false },
  { id: 'cocktail-bar', name: 'Коктейльный бар (бармен)', description: 'Бармен + 5 коктейлей: Апероль Шприц, Мохито, Космополитен, Негрони, Маргарита. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'show', format: ['furshet', 'banket'], tier: ['premium', 'luxury'], pricePerGuest: 600, servingsPerGuest: 1, allergens: [], dietBadges: [], childFriendly: false },
  { id: 'wine-sommelier', name: 'Винное сопровождение (5 вин)', description: 'Сомелье + 5 вин с рассказом о каждом, подобранных под меню. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'show', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 1200, servingsPerGuest: 1, allergens: ['sulphites'], dietBadges: ['vegan'], childFriendly: false },
  { id: 'whisky-bar', name: 'Виски-бар', description: 'Коллекция виски: бурбон, скотч, ирландский, японский. ХЕ=1, БЖУ: белки 5 г / жиры 5 г / углеводы 12 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['luxury'], pricePerGuest: 700, servingsPerGuest: 1, allergens: [], dietBadges: ['vegan', 'gluten-free'], childFriendly: false },
  { id: 'coffee-specialty', name: 'Спешелти-кофе', description: 'Бариста + эспрессо, капучино, флэт уайт. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket', 'coffee-break'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 200, servingsPerGuest: 1, allergens: ['milk'], dietBadges: ['gluten-free'], childFriendly: false },
  { id: 'beer-craft', name: 'Крафтовое пиво', description: 'Крафтовое пиво: IPA, стаут, пшеничное. ХЕ=0.5, БЖУ: белки 0 г / жиры 0 г / углеводы 6 г.', image: '', station: 'drinks', format: ['furshet', 'banket'], tier: ['standard', 'premium', 'luxury'], pricePerGuest: 280, servingsPerGuest: 2, allergens: ['gluten'], dietBadges: ['vegan'], childFriendly: false },
];

// ═══════════════════════════════════════════
// ПОЛНЫЙ КАТАЛОГ (124 SKU: 81 базовый + 14 халяль + 29 премиум-экстра)
// ═══════════════════════════════════════════
export const ALL_DISHES: Dish[] = [
  ...GLOBAL_SMALL_PLATES,
  ...PLANT_BASED,
  ...GRAZING,
  ...DESSERTS,
  ...DRINKS,
  ...FURSHET_EXTRA,
  ...BANKET_EXTRA,
  ...COFFEE_BREAK_EXTRA,
  ...WEDDING_EXTRA,
  ...KIDS,
  ...BRUNCH,
  ...HALAL,
  ...PREMIUM_EXTRA,
];

// Группировки для UI
export const DISH_CATEGORIES: Record<string, string> = {
  'cold': 'Холодные закуски',
  'hot': 'Горячие блюда',
  'desserts': 'Десерты',
  'drinks': 'Напитки',
  'show': 'Шоу-станции',
};

export const DIET_FILTERS: Record<string, string> = {
  'vegan': 'Веган',
  'gluten-free': 'Без глютена',
  'halal': 'Халяль',
  'sugar-free': 'Без сахара (СД1/СД2)',
  'nut-free': 'Без орехов',
};

// Формат → список ID для быстрого поиска
export const FORMAT_DISHES: Record<string, string[]> = {
  'furshet': ALL_DISHES.filter(d => d.format.includes('furshet')).map(d => d.id),
  'banket': ALL_DISHES.filter(d => d.format.includes('banket')).map(d => d.id),
  'coffee-break': ALL_DISHES.filter(d => d.format.includes('coffee-break')).map(d => d.id),
  'detskoe': ALL_DISHES.filter(d => d.format.includes('detskoe')).map(d => d.id),
  'mobile-furshet': ALL_DISHES.filter(d => d.format.includes('mobile-furshet')).map(d => d.id),
};
